config/routes.rb
Rails.application.routes.draw do
  root 'search_terms#new'
  resources :search_terms, only: [:new, :create]
  resources :products, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :products_seller
  has_many :sellers, through: :products_seller
end

app/models/product_aggregator.rb
class ProductAggregator
  attr_reader :search_term, :products

  def initialize(search_term)
    @search_term = search_term
    @client = Semantics3::Products.new(ENV['API_KEY'], ENV['API_SECRET'])
    @products = []
  end

  def aggregate
    begin
      @products = Product.where(term: @search_term.value)

      if @products.empty?
        @client.products_field('search', @search_term.value)
        @client.products_field('activeoffersonly', '1')
        @client.products_field('activesiteonly', '1')

        data = OpenStruct.new(@client.get_products)

        raise "[Semantics3 API] Received code #{data.code.inspect}" if data.code != 'OK'

        api_products = data.results.map { |result| OpenStruct.new(result) }

        Product.transaction do
          @products = api_products.map do |api_product|
            api_product.sitedetails.each do |site_detail|
              @seller = Seller.find_or_create_by!(name: site_detail['name'])
              site_detail['latestoffers'].each do |offer|
                offer_attrs = {
                  seller_id: @seller.id,
                  name: offer['seller'],
                  price: offer['price'],
                  currency: offer['currency'],
                  url: site_detail['url']
                }
                SellerOffer.create!(offer_attrs)
              end
            end

            product_attrs = {
              name: api_product.name,
              image_url: api_product.images.first,
              manufacturer: api_product.manufacturer,
              model: api_product.model,
              term: @search_term.value
            }

            product = Product.create!(product_attrs)
            ProductsSeller.create!(product_id: product.id, seller_id: @seller.id)
            product
          end
        end
      end
    rescue SocketError => socket_exception
      Rails.logger.error('[Semantics3 API] Unable to connect')
      Rails.logger.error(socket_exception.message)
      Rails.logger.error(socket_exception.backtrace.join("\n"))
    rescue Exception => exception
      Rails.logger.error(exception.message)
      Rails.logger.error(exception.backtrace.join("\n"))
    else
      #
    ensure
      @products
    end
  end
end

app/models/products_seller.rb
class ProductsSeller < ApplicationRecord
  belongs_to :product
  belongs_to :seller
end

app/models/search_term.rb
class SearchTerm
  attr_accessor :value
  include ActiveModel::Validations

  def initialize(value = nil)
    @value = value.try(:downcase)
  end

  validates :value, presence: true
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_many :products_seller
  has_many :products, through: :product_sellers

  has_many :offers, class_name: SellerOffer
end

app/models/seller_offer.rb
class SellerOffer < ApplicationRecord
  belongs_to :seller
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :validate_search_term, only: [:index]

  def index
    @product_aggregator = ProductAggregator.new(SearchTerm.new(product_params[:name]))
    @product_aggregator.aggregate
    @products = @product_aggregator.products
  end

  def show
    @offers = SellerOffer.where(seller_id: @product.seller_ids)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.permit(:name)
    end

    def validate_search_term
      name = product_params[:name]
      redirect_to '/' unless name.present?
    end
end

app/controllers/search_terms_controller.rb
class SearchTermsController < ApplicationController
  def new
    @search_term = SearchTerm.new
  end

  def create
    @search_term = SearchTerm.new(search_term_params[:value])
    if @search_term.valid?
      redirect_to products_path(name: @search_term.value)
    else
      render :new
    end
  end

  private
  def search_term_params
    params.require(:search_term).permit(:value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_terms_helper.rb
module SearchTermsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroSemantics</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :image_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :image_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:image_url) %>
  </div>
  <div class="form-group">
    <%= f.label :manufacturer, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :manufacturer, :class => 'form-control' %>
    </div>
    <%=f.error_span(:manufacturer) %>
  </div>
  <div class="form-group">
    <%= f.label :model, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :model, :class => 'form-control' %>
    </div>
    <%=f.error_span(:model) %>
  </div>
  <div class="form-group">
    <%= f.label :term, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :term, :class => 'form-control' %>
    </div>
    <%=f.error_span(:term) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <h4><%= link_to("Back to search", '/') %></h4>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:image_url) %></th>
      <th><%= model_class.human_attribute_name(:manufacturer) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th>Search Term used</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to(product.name, product_path(product)) %></td>
        <td><%= product.manufacturer %></td>
        <td><%= product.model %></td>
        <td><%= product.term %></td>
        <td><%= product.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      product_path(product), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => @product.name.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dd><%= image_tag(@product.image_url, size: '100x100') %></dd>
  <dt><strong><%= model_class.human_attribute_name(:manufacturer) %>:</strong></dt>
  <dd><%= @product.manufacturer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
  <dd><%= @product.model %></dd>
</dl>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Seller name</th>
      <th>Price</th>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.name %></td>
        <td><%= number_to_currency(offer.price) %> <%= offer.currency %></td>
        <td><%= link_to(offer.url, offer.url) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path(name: @product.term), :class => 'btn btn-default'  %>

app/views/search_terms/_form.html.erb
<%= simple_form_for(:search_term, url: search_terms_path) do |f| %>
  <% if @search_term.errors.any? %>
    <div id="error_explanation">
      Please enter a product name (i.e. "IPhone 7")
    </div>
  <% end %>

  <%= f.input :value, label: 'Enter a product name' %>
  <%= f.button :submit, 'Search'  %>
<% end %>

app/views/search_terms/new.html.erb
<div class="page-header">
  <h1>Search Semantics3 API</h1>
</div>
<%= render :partial => 'form' %>